on:
  push:
    branches:
      - main
name: Build and Deploy on AWS
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create back-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_JWT_SECRET: "gabriel"
          envkey_PORT: 5000
          envkey_POSTGRES_USERNAME: "postgres"
          envkey_POSTGRES_PASSWORD: "postgres"
          envkey_POSTGRES_DB: "finplus"
          envkey_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/finplus"
          directory: back-end
          file_name: .env
          fail_on_empty: true
      - name: Create front-end env file
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_REACT_APP_BRAPI_API_BASE_URL: "https://brapi.dev/"
          envkey_REACT_APP_BACK_END_URL: "http://ec2-52-91-202-18.compute-1.amazonaws.com:80/api"
          directory: front-end
          file_name: .env
          fail_on_empty: true
      - name: Build
        run: docker compose build
      - name: Run
        run: docker compose down && docker compose up -d