name: Pull Request on Github
on: [pull_request]
jobs:
  PullRequest-GitHub:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make a new envfile
        uses: SpicyPizza/create-envfile@v1.3.1
        with:
          envkey_JWT_SECRET: ${{secrets.JWT_SECRET}}
          envkey_PORT: ${{secrets.PORT}}
          envkey_POSTGRES_USERNAME: ${{secrets.POSTGRES_USERNAME}}
          envkey_POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          envkey_POSTGRES_DB: ${{secrets.POSTGRES_DB_TEST}}
          envkey_DATABASE_URL: ${{secrets.POSTGRES_URL_TEST}}
          directory: back-end
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node npm run test
